<?php session_start();
include('includes/config.php');
$user_obj = new Cl_User();
if(strlen($_SESSION['login'])==0)
{   
	$_SESSION['url'] = $_SERVER['REQUEST_URI'];
	header('location:login.php');
}
$uid = $_SESSION['id'];
$user_balance= $user_obj->get_user_coins_balance($uid);
$User_gift_coins= $user_balance['gift_coins'];
//print_r($user_balance);
if(isset($_POST['submit']) && $_SESSION["csrf_token_3"] == $_POST['csrf_token_3'])
{
$amazon_pro_name=$_POST['amazon_pro_name'];
$amazon_pro_link=$_POST['amazon_pro_link'];
$amazon_pro_price=$_POST['amazon_pro_price'];
$gift_coins_exchange_rate = $user_obj->gift_coins_exchange_rate();
echo $price = $amazon_pro_price*$gift_coins_exchange_rate;
if($User_gift_coins >= $price)
{
	$_SESSION['msg']="Your order has been submitted";
}
else
{
 $_SESSION['Err_msg']="Your Coins Balance is not enough to purchase items";  
}
/*$sql=mysqli_query($con,"insert into tickets (user_id,sub,message,attachment,is_active,created_at) values('$member_id','$sub','$body','$attachment','0',NOW())");

$sql2=mysqli_query($con,"Select ticket_id from tickets order by ticket_id desc limit 1");
$num_rows = mysqli_fetch_row($sql2);
$Invoice_number1 = $num_rows[0];

$sql2=mysqli_query($con,"insert into comments (ticket_id,user_id,sub,comment,created_at) values('$Invoice_number1','$member_id','$sub','$body',NOW())");
*/
/*Mail to admin*/
/*$to = 'preetmtharu@gmail.com';
$subject = 'New Ticket Created'.$sub;
//$from = $email;
require_once('PHPMailer/class.phpmailer.php');
$mail = new PHPMailer;
$mail->isSMTP();
$mail->Host = 'mail.giftscome.com.cp-28.hostgatorwebservers.com';
$mail->Port = 25;
$mail->SMTPAuth = true;
$mail->Username = 'info@giftscome.com.cp-28.hostgatorwebservers.com';
$mail->Password = 'Codechefs@2018';
$mail->isHTML(true);
$mailContent = '<html><body>';
$mailContent .='<p>A new ticket -Ticket'.$Invoice_number1.' generated by user on giftscome, to reply of ticekt please click on below link </p>';
$mailContent .= '<p style="color:#080;font-size:18px;"><a href='.SITE_URL.'admin/support_us.php> '.SITE_URL.'admin/support_us.php </a></p>';
$mailContent .= '</body></html>';
$mail->setFrom("info@giftscome.com.cp-28.hostgatorwebservers.com","Giftscome");
$mail->addAddress($to);
$mail->Subject = $subject;
$mail->msgHTML($mailContent);
$mail->Body = ($mailContent);
$mail->send();
// Success or Failure
// if(!$mail->send())
    // {
	// return 'fail';
	// }else
	// {
   // return 'success';
	// }
*/
}
?>
<!DOCTYPE html>
<head>
<title>Amazon Self Select Gift</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php require_once('templates/common_css.php');?>
<link rel="stylesheet" href="css/support_ticket.css" />
<style>
span.help-block {
    color: red !important;
    display: block !important;
}
</style>
</head>
<body class="animsition" onLoad="start()">
<?php require_once('templates/header.php');?>
	<!-- Title Page -->
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url(images/gamesbanner1.png);"><h2 style="color:#fff;">Amazon Self Select Gift</h2></section>
	<!-- content page -->
	<section class="bgwhite p-t-66 p-b-38">
		<div class="container">
			<div class="row">
			<?php if(!empty($_SESSION['msg'])){?>
			                    <div class="col-md-12">
								<div class="alert alert-success" id="successMessage">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<strong>Well done!</strong>	<?php echo htmlentities($_SESSION['msg']);?><?php echo htmlentities($_SESSION['msg']="");?>
								</div>
								</div>
			<?php } ?>
			<?php if(!empty($_SESSION['Err_msg'])){?>
			                    <div class="col-md-12">
								<div class="alert alert-danger" id="successMessage">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<strong>Oops!</strong>	<?php echo htmlentities($_SESSION['Err_msg']);?><?php echo htmlentities($_SESSION['Err_msg']="");?>
								</div>
								</div>
			<?php } ?>
				<div class="col-md-12 p-b-30">
					<h3 class="m-text26 p-t-15 p-b-16">Post a Ticket For Amazon Self Select Gift Item</h3>
					
					 <form method="post" action=""  name="gen_tct" id="gen_tct" enctype="multipart/form-data" method="post">
                    <div class="form-group">
                      <label class="control-label mb-10 text-left">Product Name* </label>
                      <input type="text" name="amazon_pro_name" id="amazon_pro_name" class="form-control textbox" value="" placeholder="" required>
					  <span class="help-block"></span>
                    </div>
					
					 <div class="form-group">
                      <label class="control-label mb-10 text-left">Product Link* </label>
                      <input type="text" name="amazon_pro_link" id="amazon_pro_link" class="form-control textbox" value="" placeholder="" required>
					  <span class="help-block"></span>
                    </div>
					
					 <div class="form-group">
                      <label class="control-label mb-10 text-left">Product Price* (In $) </label>
                      <input type="text" name="amazon_pro_price" id="amazon_pro_price" class="form-control textbox" value="" placeholder="" required>
					  <span class="help-block"></span>
                    </div>
					
					<?php $_SESSION["csrf_token_3"] = md5(rand(0,10000000)).time(); ?>
				<input type="hidden" name="csrf_token_3" value="<?php echo htmlspecialchars($_SESSION["csrf_token_3"]);?>">
					<input type="submit" class="btn btn-success btn-anim" name="submit" value="Submit" required>
                  </form>
				</div>
							
			</div>
			
			
</div>
</section>
<?php require_once('templates/footer.php');?>
<?php require_once('templates/common_js.php');?>
<script src="js/jquery.validate.min.js"></script>
<script type="text/javascript" src="js/additional-methods_new.js"></script>
<!-- jQuery Form Validation code -->
<script type="text/javascript"> 
	$(document).ready(function(){
 // Setup form validation on the #register-form element
 $("#gen_tct").validate({
 	submitHandler : function(e) {
 		$(form).submit();
 	},
        // Specify the validation rules
        rules : {
        	amazon_pro_name : {required : true },
        	amazon_pro_link : {required : true },
			amazon_pro_price : {required : true,digits:true }
			},
        // Specify the validation error messages
        messages: {
        	amazon_pro_name : {required : "Please enter amazon product name"},
			amazon_pro_link : {required : "Please enter amazon product url"	},
			amazon_pro_price : {required : "Please enter amazon product price"},
			
		},
		errorPlacement : function(error, element) {
			$(element).closest('div').find('.help-block').html(error.html());
		},
		highlight : function(element) {
			$(element).closest('div').removeClass('has-success').addClass('has-error');
		},
		unhighlight: function(element, errorClass, validClass) {
			$(element).closest('div').removeClass('has-error').addClass('has-success');
			$(element).closest('div').find('.help-block').html('');
		}
	});

});
</script>
<!--<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>-->
<?php //require_once('templates/chat_script.php');?>
<script>
	$(document).ready(function(){
		setTimeout(function() {
			$('#successMessage').fadeOut('fast');
        }, 10000); // <-- time in milliseconds
	});
</script>
</body>
</html>