<?php session_start();
include('includes/config.php');
$user_obj = new Cl_User();
$member_id = $_SESSION['id'];
if(isset($_POST['create']))
{
$sub=$_POST['subject'];
$body=$_POST['message'];
$attachment=$_FILES["attachment"]["name"];
move_uploaded_file($_FILES["attachment"]["tmp_name"],"uploads/tickets/".$_FILES["attachment"]["name"]);
$sql=mysqli_query($con,"insert into tickets (user_id,sub,message,attachment,is_active,created_at) values('$member_id','$sub','$body','$attachment','0',NOW())");

$sql2=mysqli_query($con,"Select ticket_id from tickets order by ticket_id desc limit 1");
$num_rows = mysqli_fetch_row($sql2);
$Invoice_number1 = $num_rows[0];

$sql2=mysqli_query($con,"insert into comments (ticket_id,user_id,sub,comment,created_at,status_by_user) values('$Invoice_number1','$member_id','$sub','$body',NOW(),'1')");

$_SESSION['msg']="Ticket submitted Successfully!!";
/*Email to admin*/
$site_setting =$user_obj->get_general_setting();
$admin_email = $site_setting['site_email'];
$to = $admin_email;
//$to = 'preetmtharu@gmail.com';
$subject = 'New Ticket Created '.$sub;
$msg ='<p>Hi, <br /><br /> A new ticket -Ticket'.$Invoice_number1.' generated by user on giftscome, to reply of ticekt please click on below link </p><p style="color:#080;font-size:18px;"><a href='.SITE_URL.'/admin/support_us.php> '.SITE_URL.'/admin/support_us.php </a></p>';
$user_obj->send_email($to,$subject,$msg);
}
?>
<script type="text/javascript">
setTimeout(function () {
var basepath = window.location.protocol + '//' + window.location.hostname;
var path = basepath + '/support_us.php';
window.location.href= path; // the redirect goes here
},1000); // 5 seconds
</script>
